receivers:
  otlp:
    protocols:
      grpc: 4200
      http: 4200

processors:
  batch:

exporters:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,zipkin]