receivers:
  otlp:
    protocols:
      grpc: 4317
      http: 4317

processors:
  batch:

exporters:
  zipkin:
    endpoint: "https://localhost:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,zipkin]